[theme]
base = "dark"
primaryColor = "#A8617A"
backgroundColor = "#290C19"
secondaryBackgroundColor = "#401527"
textColor = "#F6E8EC"
linkColor = "#E8B9C9"
borderColor = "#875166"
showSidebarBorder = true

[theme.sidebar]
primaryColor = "#B8758D"
backgroundColor = "#340f20"
secondaryBackgroundColor = "#683149"
textColor = "#F6E8EC"
borderColor = "#59152c"
